<style>
	#dropdown
	{
		position: absolute;
		top: 70px;
		right: 20px;
		visibility: hidden;
		float:right;
	}
	.last:hover #dropdown
	{
		visibility: visible;
	}
</style>
<div class="block block-login" id="dropdown">
	<div class="block-title">
		<strong><span><?php echo $this->__('Login') ?></span></strong>
	</div>
	<form action="<?php echo $this->getUrl('customer/account/loginPost') ?>" method="post">
		<?php echo $this->getBlockHtml('formkey'); ?>
		<div class="block-content">
			<label for="mini-login"><?php echo $this->__('Email:') ?></label><input type="text" name="login[username]" id="mini-login" class="input-text" />
			<label for="mini-password"><?php echo $this->__('Password:') ?></label><input type="password" name="login[password]" id="mini-password" class="input-text" />
			<div class="actions">
				<button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
			</div>
		</div>
	</form>
</div>