<?php
/**
 * @category   Inchoo
 * @package    Inchoo_AddAllToCart
 * @author     Mladen Lotar - mladen.lotar@surgeworks.com
 *
 * @warning    Please don't install this extension to your site, it was created as April fools joke
 */
?>

<span id="inchoo-add-everything">
	<a href="<?php echo Mage::getUrl('emptyCart/index/addEverything/')?>">
		<?php echo Mage::helper('core')->__("BUY ALL");?>
	</a>
</span>
